### ISSUE TITLE
Balance update request adds funds to the balance

### ISSUE THREAD

**Issue by Meiendorf** [nurlandadasev/mobile-banking-app#1]
Добрый день. 
Меня зовут Роман, мы, совместно с @aandrey1993 проводим ревью тестового задания. 
По ходу ревью будем открывать тикеты с вопросами/предложениями для улучшения кода.

## Описание
В запросе на обновление баланса к балансу прибавляется значение, полученное от клиента, вместо перезаписывания баланса полностью: 
https://github.com/nurlandadasev/mobile-banking-app/blob/d2b87c776864f568ae5d211b8d456772533e3aec/src/main/java/com/ma/mobilebankingapp/services/impl/AccountServiceImpl.java#L91

Это немного не интуитивное поведение. Нужно либо в описании к запросу об этом написать, либо полностью перезаписывать значение баланса.

**Comment by nurlandadasev** [comment]
Добры день! Хорошо я сделаю изменения над своим кодом.
