### ISSUE TITLE
Wrong component Inject

### ISSUE THREAD

**Issue by aandrey1993** [nurlandadasev/mobile-banking-app#3]
## Описание
При определении сервиса `AccountServiceImpl`, зависимые репозитории инжектятся с помощью анотации lombok `@RequiredArgsConstructor`, что является не самой хорошей практикой использования DI. 

![изображение](https://user-images.githubusercontent.com/49781313/119997265-39e3be80-bfd8-11eb-9c74-e27c6ba27799.png)

Исправьте, пожалуйста, внедрение зависимостей во всех компонентов, чтобы она выполнялась явно через конструктор, используя аннотацию `@Autowired`

**Comment by nurlandadasev** [comment]
Спасибо за информацию.
Сменю все внедрения зависимостей через конструктор.
