### ISSUE TITLE
Returning ResponseEntity from service methods

### ISSUE THREAD

**Issue by aandrey1993** [nurlandadasev/mobile-banking-app#4]
## Описание
При запросе всех счетов, из методов сервиса `AccountServiceImpl` (`getAccounts`, `getAccountsWithFiltering`), сразу возвращается объект ResponseEntity, что не является хорошей практикой.

![изображение](https://user-images.githubusercontent.com/49781313/119997882-dd34d380-bfd8-11eb-800b-ff40479a4d03.png)

Формированием ответа `ResponseEntity` должен заниматься контроллер, сервис же должен вернуть просто список найденных объектов.

Исправьте, пожалуйста, данный момент.

**Comment by nurlandadasev** [comment]
Хорошо буду иметь в виду.
