### ISSUE TITLE
Using ORM to work with the database

### ISSUE THREAD

**Issue by aandrey1993** [nurlandadasev/mobile-banking-app#5]
## Описание
Подскажите, пожалуйста,  по каким причинам был выбран ORM для работы с базой данных и какие способы вызова хранимых процедур вам известны ?  (С использованием любых инструментов)

**Comment by nurlandadasev** [comment]
Я считаю одним из главных плюсов ORM возможность обращаться к БД не на прямую а реализовать это с помощью Java классов. ORM избавляет нас от реализации БД в ручную так как делает многое сам. В итоге это ускоряет разработку приложения. 

Можно работать с базой данных с помощью JDBC (Statement, PreparedStatement).
